documentInfo:
  documentclass: jsbook
  documentoptions:
    - uplatex
    - a4paper
    - 10pt
    - oneside
    - onecolumn
    - openany
  fontpreset: ipaex
  title:
    ja: テスト文章
  date:
    year: 2017
    month: 6
  authors:
    - name:
        en: 山田 太郎
